vich_uploader:
    db_driver: orm

    mappings:
       media:
           uri_prefix: /media
           upload_destination: '%kernel.project_dir%/public/media'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       pdf:
           uri_prefix: /media/pdf
           upload_destination: '%kernel.project_dir%/public/media/pdf'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
